theme: jekyll-theme-minimal
title: Kyle Lin
description: As a Senior Digital Experience Designer, Kyle leads Continuum’s digital discipline. He believes strongly that effective innovation should come from artfully balancing the needs and interests of both business and customers through human-centered design. He considers that the greatest merit of technology - always being flexible and ready to be morphed and honed according to its users many-faceted needs.
show_downloads: false

